name: Clojure CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout (GitHub)
      uses: actions/checkout@v4
      with:
        submodules: true
        token: ${{ secrets.AOC_INPUTS_TOKEN }}

    - name: Build and run Dev Container tasks
      uses: devcontainers/ci@v0.3
      with: 
        runCmd: |
          # Install dependencies
          lein deps
          # Run tests
          lein tests
